### ISSUE TITLE
How to solve 'AttributeError: 'EasyDict' object has no attribute 'iteritems''?

### ISSUE THREAD

**Issue by b2220333** [tohinz/multiple-objects-gan#3]
Now I download this package just want to test pre-train model.
I run this package as follows:

```
git clone https://github.com/tohinz/multiple-objects-gan
cd multiple-objects-gan
vim requirements.txt to del pkg-resources==0.0.0 and change tensorboard==1.0.0a4 to tensorboard==1.6.0rc0 to prevent errors.
pip install -r requirements.txt
cd models/
wget -c https://www2.informatik.uni-hamburg.de/wtm/software/multiple-objects-gan/model-ms-coco-attngan.zip
unzip model-ms-coco-attngan.zip
cd ../code/coco/attngan/
python3 main.py --cfg cfg/coco_eval.yml
```

I got the error:

```
(t3) sam@sam-ub1804:~/PycharmProjects/t3/multiple-objects-gan/code/coco/attngan$ python3 main.py --cfg cfg/coco_eval.yml
Traceback (most recent call last):
  File "main.py", line 92, in <module>
    cfg_from_file(args.cfg_file)
  File "/home/sam/PycharmProjects/t3/multiple-objects-gan/code/coco/attngan/miscc/config.py", line 106, in cfg_from_file
    _merge_a_into_b(yaml_cfg, __C)
  File "/home/sam/PycharmProjects/t3/multiple-objects-gan/code/coco/attngan/miscc/config.py", line 74, in _merge_a_into_b
    for k, v in a.iteritems():
AttributeError: 'EasyDict' object has no attribute 'iteritems'
(t3) sam@sam-ub1804:~/PycharmProjects/t3/multiple-objects-gan/code/coco/attngan$
```

How to solve it? Am I missing something?
Thank you~

**Comment by tohinz** [comment]
Hi, you’re using Python 3.
You just need to replace „a.iteritems()“ with „a.items()“ (Check out this link: https://stackoverflow.com/questions/30418481/error-dict-object-has-no-attribute-iteritems). 
You might have to change 1-2 other small things in the code if you’re using Python 3 (nothing too complicated though, but I guess you’ll get another 1-2 or more exceptions that you’d need to fix before it works with Python 3). 
Otherwise it might be easier to use Python 2 if you just want to run the model.

**Comment by b2220333** [comment]
OK, I found that python2 do not show this problem.
Thank you~~
